import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import CategoryList from "@/components/CategoryList/CategoryList";
import OrderList from "@/components/OrderList";
import { OrderProvider } from "@/context/OrderContext";
import { prisma } from "@/lib/prisma";
import { Category } from "@prisma/client";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories: Category[] = await prisma.category.findMany({});
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <OrderProvider>
          <div className="grid-cols-24 grid-rows-24 grid h-screen w-screen">
            <CategoryList categories={categories} />
            {children}
            <OrderList />
          </div>
        </OrderProvider>
      </body>
    </html>
  );
}
