name: Restrict Merges to Main

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

jobs:
  restrict-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        if: ${{ github.base_ref == 'main' && github.head_ref != 'dev' }}
        run: |
          echo "Pull requests to 'main' must come from 'dev' branch."
          exit 1
